use_frameworks!

target 'DanmakuKit_Example' do
  pod 'DanmakuKit', :path => '../', :subspecs => ['Core', 'Gif']
  
  pod 'KVOController', '1.2.0'
  pod 'DeviceKit', '~> 4.0'
  pod 'SwiftyJSON', '~> 4.0'

  target 'DanmakuKit_Tests' do
    inherit! :search_paths

    
  end
end
