use_frameworks!

target 'DanmakuKit_Example' do
  pod 'DanmakuKit', :path => '../', :subspecs => ['Core', 'Gif', 'SwiftUI']
  
  pod 'DeviceKit', '~> 4.0'
  pod 'SwiftyJSON', '~> 5.0.0'

  target 'DanmakuKit_Tests' do
    inherit! :search_paths

    
  end
end
